import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Existing VoiceShield dark theme
        navy: {
          950: "#05070d",
          900: "#0a0e18",
          800: "#0f1524",
          700: "#161d33",
        },
        // Stitch Material Design 3 color tokens
        "on-secondary": "#ffffff",
        "surface-dim": "#d2d9f4",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#93ccff",
        "on-secondary-fixed": "#00201d",
        "tertiary-fixed-dim": "#4cd7f6",
        "surface-container-highest": "#dae2fd",
        "on-primary-fixed-variant": "#004b73",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "secondary-fixed": "#89f5e7",
        "surface-variant": "#dae2fd",
        "inverse-surface": "#283044",
        "on-background": "#131b2e",
        "primary-fixed-dim": "#93ccff",
        "on-surface-variant": "#3f4850",
        "on-tertiary-container": "#f9fdff",
        "on-tertiary-fixed": "#001f26",
        "primary-container": "#007bb9",
        "on-secondary-container": "#006f66",
        "surface-tint": "#006398",
        "tertiary-fixed": "#acedff",
        "secondary": "#006a61",
        "secondary-fixed-dim": "#6bd8cb",
        "primary": "#006194",
        "surface-container-low": "#f2f3ff",
        "tertiary": "#006577",
        "tertiary-container": "#008096",
        "on-surface": "#131b2e",
        "outline": "#707881",
        "surface-container": "#eaedff",
        "on-error": "#ffffff",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#004e5c",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#005049",
        "surface-bright": "#faf8ff",
        "surface-container-high": "#e2e7ff",
        "on-primary-container": "#fdfcff",
        "on-primary": "#ffffff",
        "outline-variant": "#bfc7d2",
        "secondary-container": "#86f2e4",
        "on-primary-fixed": "#001d31",
        "error-container": "#ffdad6",
        "primary-fixed": "#cce5ff",
        "background": "#faf8ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2.5rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "margin": "2rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Space Grotesk", "system-ui"],
        "display-hero-mobile": ["Space Grotesk", "system-ui"],
        "mono-metric": ["JetBrains Mono", "monospace"],
        "mono-badge": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "system-ui"],
        "headline-md": ["Space Grotesk", "system-ui"],
        "display-hero": ["Space Grotesk", "system-ui"],
        "headline-sm": ["Space Grotesk", "system-ui"],
        "body-sm": ["Inter", "system-ui"],
        "mono-label": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "system-ui"],
        "headline-lg": ["Space Grotesk", "system-ui"],
      },
      fontSize: {
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-metric": ["16px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "mono-badge": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["22px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "mono-label": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
      backdropBlur: {
        xs: "2px",
        xl: "20px",
      },
    },
  },
  plugins: [],
};

export default config;
